# Generated by Django 4.0.5 on 2022-12-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamepark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamepark_name', models.CharField(max_length=50, verbose_name='gamepark_name')),
                ('contact', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, default='null', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warden_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wildlife_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spices_type', models.CharField(max_length=40)),
                ('no_of_spices', models.IntegerField()),
                ('recieved_by', models.CharField(default='missing', max_length=100)),
                ('warden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.warden')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=20)),
                ('gamepark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.gamepark')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_paid', models.IntegerField()),
                ('recieved_by', models.CharField(default='missing', max_length=100)),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.visitor')),
            ],
        ),
    ]
